### ISSUE TITLE
아카이브 기능 추가

### ISSUE THREAD

**Issue by YumYumNyang** [bannsi/bansi-server#6]
- 폴더 만들기 
- 폴더 삭제하기
- 폴더 수정하기
- 아카이빙 시 폴더 선택
- 링크 아카이브 : 유튜브 링크인 경우 시간대 리스트 
- 조각 아카이브
- 조각모음 아카이브

**Comment by zzzinho** [comment]
아카이브하는 piece랑 collection를 폴더 없이 아카이빙할 수 있나요?

**Comment by YumYumNyang** [comment]
흠.. 폴더가 꼭 있도록 만들어주는게 좋을것 같아요!

2022년 3월 23일 (수) 오후 3:01, Jinho ***@***.***>님이 작성:

**Comment by zzzinho** [comment]
아카이브 기능 추가 했습니닷
